#! /bin/bash 

case $BUTTON in
    1) thunderbird &;;
    2) notify-send "Clock" "Click for Calendar Right click for Mails" &;;
    3) kitty -e nvim "$0" &;;
esac

dte="$(date +"%a %b-%d %l:%M%p"| sed 's/  / /g')"
echo -e "$dte "
