#! /bin/bash 
case $BUTTON in
    1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
    2) kitty -e /home/sanjay/anaconda3/bin/bpytop &;;
	3) kitty -e nvim "$0" &;;
esac

temp="$(python ~/applications/dwmblocks/scripts/cpu.py)"
echo -e "$temp "
