#! /bin/bash 
case $BUTTON in
	1) notify-send "🧠 GPU Details" "$(nvidia-smi)" &;;
	#2) notify-send "Nvidia GPU" "\- Shows GPU Temp.";;
	2) kitty -e nvidia-settings &;;
	3) kitty -e nvim "$0" &;;
	
	

esac


temp="$(nvidia-settings -q gpucoretemp | awk 'NR==2{print substr($4,1,2) }')"
echo -e "$temp°C "
