#! /bin/bash 
case $BUTTON in
	1) notify-send "🧠 Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
    2) notify-send "🧠 Memory module" "\- Shows Memory Used.";;
	3) st -e htop ;;
esac


mem="$(free -h | awk '/^Mem:/ {print $3}')"
echo -e "$mem "
