#!/bin/bash

case $BUTTON in
	1) kitty -e paru -Syu &;;
	#2) notify-send "Pamac Update" "Click for update Right click for pacman";;
	2) pamac-manager &;;
	3) kitty -e nvim "$0" &;;
	
	

esac


cupd=$(checkupdates | wc -l)
echo -e "$cupd "
