#! /bin/bash 
case $BUTTON in
    1) playerctl play-pause spotify ;;
    2) notify-send "Play Previous";;
	3) kitty -e nvim "$0" ;;
esac

temp="$(~/applications/dwmblocks/scripts/scroll_spotify_status.sh)"
echo -e "$temp "
