#!/bin/bash 

case $BUTTON in
	1) pavucontrol ;;
	2) notify-send "Volume" "Click for Settings
    Right click for equalizer";;
	3) pulseaudio-equalizer-gtk ;;
	
	

esac


mute="$(amixer get Master|tail -1|awk '{print $6}')"
output=""
if [ "$mute" = "[off]" ]; then  
    output="🔇 M"
else
    vol="$(amixer get Master|tail -1|awk '{print $5}'|tr [ ' '|tr ] ' '|tr % ' ')"
    vol=$(($vol + 0))
    #echo "${vol}% "
    if [ $vol -lt 30 ]; then
        output=" ${vol}% "
    elif [ $vol -lt 60 ]; then
        output=" ${vol}% "
    else
        output=" ${vol}% "
    fi
fi
echo -e "$output"
