#!/bin/bash 
mute="$(amixer get Master|tail -1|awk '{print $6}')"
output=""
if [ "$mute" = "[off]" ]; then  
    output="🔇 M"
else
    vol="$(amixer get Master|tail -1|awk '{print $5}'|tr [ ' '|tr ] ' '|tr % ' ')"
    vol=$(($vol + 0))
    #echo "${vol}% "
    if [ $vol -lt 30 ]; then
        output=" ${vol}% "
    elif [ $vol -lt 60 ]; then
        output=" ${vol}% "
    else
        output=" ${vol}% "
    fi
fi
echo -e "\x04 $output"
